/*
 * exceptionBuilderUndef.h
 *
 *  Created on: 17.3.2010
 *      Author: ondra
 */

#ifdef LIGHTSPEED_EXCEPTIONBUILDER_H_
#undef LIGHTSPEED_EXCEPTIONBUILDER_H_

#undef LIGHTSPD_DEF_EXCEPTION
#undef LIGHTSPD_EXCEPTION_PAR_0
#undef LIGHTSPD_EXCEPTION_PAR_1
#undef LIGHTSPD_EXCEPTION_PAR_2
#undef LIGHTSPD_EXCEPTION_PAR_3
#undef LIGHTSPD_EXCEPTION_PAR_4
#undef LIGHTSPD_EXCEPTION_PAR_5
#undef LIGHTSPD_END_EXCEPTION
#undef LIGHTSPD_EXCEPTION_MSG


#endif /* EXCEPTIONBUILDER_H_ */
