Document: liblightspeed
Title: Debian liblightspeed Manual
Author: <insert document author here>
Abstract: This manual describes what liblightspeed is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblightspeed/liblightspeed.sgml.gz

Format: postscript
Files: /usr/share/doc/liblightspeed/liblightspeed.ps.gz

Format: text
Files: /usr/share/doc/liblightspeed/liblightspeed.text.gz

Format: HTML
Index: /usr/share/doc/liblightspeed/html/index.html
Files: /usr/share/doc/liblightspeed/html/*.html
